-- Таблица заказов
CREATE TABLE
IF NOT EXISTS `avs_booking_orders`
(
    `ID` INT
(11) NOT NULL AUTO_INCREMENT,
    `ORDER_NUMBER` VARCHAR
(50) NOT NULL,
    `PAVILION_ID` INT
(11) NOT NULL,
    `PAVILION_NAME` VARCHAR
(255) NOT NULL,
    `LEGAL_ENTITY` VARCHAR
(50) NOT NULL,
    `CLIENT_NAME` VARCHAR
(255) NOT NULL,
    `CLIENT_PHONE` VARCHAR
(50) NOT NULL,
    `CLIENT_EMAIL` VARCHAR
(255) DEFAULT NULL,
    `CLIENT_TG_ID` VARCHAR
(50) DEFAULT NULL,
    `START_TIME` DATETIME NOT NULL,
    `END_TIME` DATETIME NOT NULL,
    `NEW_START_TIME` DATETIME DEFAULT NULL,
    `NEW_END_TIME` DATETIME DEFAULT NULL,
    `NEW_PAVILION_ID` INT
(11) DEFAULT NULL,
    `NEW_PAVILION_NAME` VARCHAR
(255) DEFAULT NULL,
    `EXTENDED_END_TIME` DATETIME DEFAULT NULL,
    `PRICE` DECIMAL
(10,2) NOT NULL,
    `DEPOSIT_AMOUNT` DECIMAL
(10,2) NOT NULL,
    `DISCOUNT_AMOUNT` DECIMAL
(10,2) DEFAULT 0,
    `DISCOUNT_CODE` VARCHAR
(50) DEFAULT NULL,
    `STATUS` ENUM
('pending','paid','confirmed','active','completed','cancelled','deleted') DEFAULT 'pending',
    `PAYMENT_ID` VARCHAR
(100) DEFAULT NULL,
    `PAYMENT_STATUS` VARCHAR
(50) DEFAULT 'pending',
    `PAID_AMOUNT` DECIMAL
(10,2) DEFAULT 0,
    `LIBREBOOKING_RESERVATION_ID` VARCHAR
(100) DEFAULT NULL,
    `RENTAL_TYPE` VARCHAR
(20) DEFAULT NULL,
    `DURATION_HOURS` INT
(11) DEFAULT 0,
    `COMMENT` TEXT DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `DELETED_AT` DATETIME DEFAULT NULL,
    `DELETED_BY` INT
(11) DEFAULT 0,
    PRIMARY KEY
(`ID`),
    UNIQUE KEY `idx_order_number`
(`ORDER_NUMBER`),
    KEY `idx_pavilion_id`
(`PAVILION_ID`),
    KEY `idx_status`
(`STATUS`),
    KEY `idx_created_at`
(`CREATED_AT`),
    KEY `idx_payment_id`
(`PAYMENT_ID`),
    KEY `idx_legal_entity`
(`LEGAL_ENTITY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Таблица особых дат
CREATE TABLE
IF NOT EXISTS `avs_booking_special_dates`
(
    `ID` INT
(11) NOT NULL AUTO_INCREMENT,
    `PAVILION_ID` INT
(11) NOT NULL,
    `DATE` DATE NOT NULL,
    `RESTRICTION_TYPE` VARCHAR
(50) NOT NULL,
    `ALLOWED_TYPES` VARCHAR
(255) DEFAULT NULL,
    `PRICE_MODIFIER` DECIMAL
(5,2) DEFAULT NULL,
    `DESCRIPTION` VARCHAR
(255) DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    PRIMARY KEY
(`ID`),
    UNIQUE KEY `idx_pavilion_date`
(`PAVILION_ID`, `DATE`),
    KEY `idx_date`
(`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Таблица скидок и промокодов
CREATE TABLE
IF NOT EXISTS `avs_booking_discounts`
(
    `ID` INT
(11) NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR
(50) NOT NULL,
    `NAME` VARCHAR
(255) NOT NULL,
    `DISCOUNT_TYPE` ENUM
('percent','fixed') NOT NULL,
    `DISCOUNT_VALUE` DECIMAL
(10,2) NOT NULL,
    `VALID_FROM` DATETIME DEFAULT NULL,
    `VALID_TO` DATETIME DEFAULT NULL,
    `MIN_ORDER_AMOUNT` DECIMAL
(10,2) DEFAULT NULL,
    `MAX_USES` INT
(11) DEFAULT NULL,
    `USES_COUNT` INT
(11) DEFAULT 0,
    `PAVILION_IDS` VARCHAR
(255) DEFAULT NULL,
    `ACTIVE` ENUM
('Y','N') DEFAULT 'Y',
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY
(`ID`),
    UNIQUE KEY `idx_code`
(`CODE`),
    KEY `idx_active`
(`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Таблица логов
CREATE TABLE
IF NOT EXISTS `avs_booking_log`
(
    `ID` INT
(11) NOT NULL AUTO_INCREMENT,
    `ACTION` VARCHAR
(100) NOT NULL,
    `ORDER_ID` INT
(11) DEFAULT 0,
    `USER_ID` INT
(11) DEFAULT 0,
    `MESSAGE` TEXT DEFAULT NULL,
    `IP_ADDRESS` VARCHAR
(45) DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY
(`ID`),
    KEY `idx_action`
(`ACTION`),
    KEY `idx_order_id`
(`ORDER_ID`),
    KEY `idx_created_at`
(`CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Таблица уведомлений
CREATE TABLE
IF NOT EXISTS `avs_booking_notifications`
(
    `ID` INT
(11) NOT NULL AUTO_INCREMENT,
    `ORDER_ID` INT
(11) NOT NULL,
    `TYPE` VARCHAR
(50) NOT NULL,
    `RECIPIENT` VARCHAR
(255) NOT NULL,
    `CHANNEL` VARCHAR
(50) NOT NULL,
    `STATUS` VARCHAR
(50) DEFAULT 'sent',
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY
(`ID`),
    KEY `idx_order_id`
(`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Таблица истории цен
CREATE TABLE
IF NOT EXISTS `avs_booking_price_history`
(
    `ID` INT
(11) NOT NULL AUTO_INCREMENT,
    `PAVILION_ID` INT
(11) NOT NULL,
    `PRICE_HOUR` DECIMAL
(10,2) DEFAULT NULL,
    `PRICE_DAY` DECIMAL
(10,2) DEFAULT NULL,
    `PRICE_NIGHT` DECIMAL
(10,2) DEFAULT NULL,
    `EFFECTIVE_FROM` DATE NOT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY
(`ID`),
    KEY `idx_pavilion_id`
(`PAVILION_ID`),
    KEY `idx_effective_from`
(`EFFECTIVE_FROM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;